### PR TITLE
Create subschema for input variable value

### PR DESCRIPTION
**Pull request by jfsiii**
# Summary

Changes to `default` on input variables based on discussion in https://github.com/elastic/package-spec/issues/96

  * Adds a new definition / subschema for values
    https://github.com/elastic/package-spec/blob/f611680b7bd7b69d0f64784ae4ba842e9fd1d183/versions/1/data_stream/manifest.spec.yml#L12-L21
  * `default` property references that definition
    https://github.com/elastic/package-spec/blob/f611680b7bd7b69d0f64784ae4ba842e9fd1d183/versions/1/data_stream/manifest.spec.yml#L86-L88
  *  Adds some more `examples` 
    https://github.com/elastic/package-spec/blob/f611680b7bd7b69d0f64784ae4ba842e9fd1d183/versions/1/data_stream/manifest.spec.yml#L22-L34
    
## Tests
<details><summary><code>make update && make check && make test</code> passes</summary>

```
go: found golang.org/x/lint/golint in golang.org/x/lint v0.0.0-20201208152925-83fdc39ff7b5
go: golang.org/x/tools upgrade => v0.0.0-20201215192005-fa10ef0b8743
Specs are up to date!
=== RUN   TestBundledSpecs
--- PASS: TestBundledSpecs (0.00s)
PASS
ok  	github.com/elastic/package-spec/code/go/internal	0.067s
?   	github.com/elastic/package-spec/code/go/internal/spec	[no test files]
=== RUN   TestValidationErrorsMultiple
--- PASS: TestValidationErrorsMultiple (0.00s)
=== RUN   TestValidationErrorsSingle
--- PASS: TestValidationErrorsSingle (0.00s)
=== RUN   TestValidationErrorsNone
--- PASS: TestValidationErrorsNone (0.00s)
=== RUN   TestNewPackage
=== RUN   TestNewPackage/no_spec_version
=== RUN   TestNewPackage/good
=== RUN   TestNewPackage/non_existent
=== RUN   TestNewPackage/no_manifest
--- PASS: TestNewPackage (0.00s)
    --- PASS: TestNewPackage/no_spec_version (0.00s)
    --- PASS: TestNewPackage/good (0.00s)
    --- PASS: TestNewPackage/non_existent (0.00s)
    --- PASS: TestNewPackage/no_manifest (0.00s)
=== RUN   TestNewSpec
--- PASS: TestNewSpec (0.00s)
PASS
ok  	github.com/elastic/package-spec/code/go/internal/validator	0.064s
?   	github.com/elastic/package-spec/code/go/internal/yamlschema	[no test files]
=== RUN   TestValidateFile
=== RUN   TestValidateFile/bad_deploy_variants
=== RUN   TestValidateFile/missing_pipeline_dashes
=== RUN   TestValidateFile/missing_image_files
=== RUN   TestValidateFile/good
=== RUN   TestValidateFile/deploy_docker
=== RUN   TestValidateFile/input_template
--- PASS: TestValidateFile (0.18s)
    --- PASS: TestValidateFile/bad_deploy_variants (0.03s)
    --- PASS: TestValidateFile/missing_pipeline_dashes (0.03s)
    --- PASS: TestValidateFile/missing_image_files (0.03s)
    --- PASS: TestValidateFile/good (0.08s)
    --- PASS: TestValidateFile/deploy_docker (0.01s)
    --- PASS: TestValidateFile/input_template (0.00s)
=== RUN   TestValidateItemNotAllowed
=== RUN   TestValidateItemNotAllowed/wrong_kibana_filename
--- PASS: TestValidateItemNotAllowed (0.01s)
    --- PASS: TestValidateItemNotAllowed/wrong_kibana_filename (0.01s)
PASS
ok  	github.com/elastic/package-spec/code/go/pkg/validator	0.340s
```
</details>

As does [this online validation](https://www.jsonschemavalidator.net/s/UUVndknm)

Screen Shot 2020-12-15 at 1 58 40 PM

### CODE REVIEW

**Comment by jfsiii** [comment]
I don't know if 4212bc6 should be committed or not. I saw a failed CI test to do a failed/missing `make update` so I pushed that commit 4212bc6. But now I see a 💚 CI from an hour before that commit so :shrug:

**Review by mtojek — APPROVED** [review]
That's weird behavior indeed... The change itself looks good, although let's make sure the build is green. Would you mind running the following commands?

```
make check
cd code/go
go mod tidy
```

**Comment by jfsiii** [comment]
@mtojek I ran those commands and `go mod tidy` did delete some lines from `go.mod` & `go.sum` 46e994c1e05f0519e0bd6e64a086d88289416f31

**Comment by mtojek** [comment]
The CI status is green. Feel free to merge it.

**Pull request merged**
