### PR TITLE
Add new validations to manage object_type and metric_type fields

### PR DESCRIPTION
**Pull request by mrodm**
## What does this PR do?

This PR adds new validations to include the cases where `object_type` and/or `metric_type` are set in field definitions.

- If a field defines an `object_type` (**new**):
    - the only possible value for `type` is `object`.
- If a field defines a `metric_type` and an `object_type` 
    - currently, `aggregate_metric_double` not allowed.
    - `object_type` just could have a different value of possible values:
        - histogram
        - long
        - integer
        - short
        - byte
        - double
        - float
        - half_float
        - scaled_float
        - unsigned_long
- If a field defines a `metric_type` but it does not define an `object_type` 
    - `type` just could have these allowed values:
        - histogram
        - aggregate_metric_double
        - long
        - integer
        - short
        - byte
        - double
        - float
        - half_float
        - scaled_float
        - unsigned_long

This PR allows field definitions like this:
```yaml
- name: prometheus.*.value
  type: object
  object_type: double
  object_type_mapping_type: "*"
  metric_type: gauge
  descriptoin: Prometheus gauge metric
```
Previously, it was failing with this error:
>    1. file "/home/mariorodriguez/Coding/work/integrations/build/packages/aws-1.46.6.zip/data_stream/cloudwatch_metrics/fields/package-fields.yml" is invalid: field 1.type: 1.type must be one of the following: "histogram", "aggregate_metric_double", "long", "integer", "short", "byte", "double", "float", "half_float", "scaled_float", "unsigned_long"

## Why is it important?

This new validation will check that the types of the fields will be the right ones when `metric_type` is set for a field (gauge or counter). Not all types are valid when this is enabled. Based on this [doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html#time-series-metric)

## Checklist

- [x] I have added test packages to [`test/packages`](https://github.com/elastic/package-spec/tree/main/test/packages) that prove my change is effective.
- [x] I have added an entry in [`spec/changelog.yml`](https://github.com/elastic/package-spec/blob/main/spec/changelog.yml).
- [x] Added JSON Patches for previous versions.

## Related issues

- Relates https://github.com/elastic/kibana/issues/155004

### CODE REVIEW

**Comment by mrodm** [comment]
test integrations

**Comment by mrodm** [comment]
Latest run with integrations, the following packages have failed their check:
- azure_application_insights
- azure_billing
- hashicorp_vault

These are the errors for each packages:
- azure_application_insights
```
[2023-07-13T12:42:38.477Z] Error: checking package failed: linting package failed: found 4 validation errors:
[2023-07-13T12:42:38.477Z]    1. file "/var/lib/jenkins/workspace/est-manager_integrations_PR-6948/src/github.com/elastic/integrations/packages/azure_application_insights/data_stream/app_insights/fields/package-fields.yml" is invalid: field 0.fields.1.fields.4.type: 0.fields.1.fields.4.type must be one of the following: "object"
[2023-07-13T12:42:38.477Z]    2. file "/var/lib/jenkins/workspace/est-manager_integrations_PR-6948/src/github.com/elastic/integrations/packages/azure_application_insights/data_stream/app_insights/fields/package-fields.yml" is invalid: field 0.fields.5.type: 0.fields.5.type must be one of the following: "object"
[2023-07-13T12:42:38.477Z]    3. file "/var/lib/jenkins/workspace/est-manager_integrations_PR-6948/src/github.com/elastic/integrations/packages/azure_application_insights/data_stream/app_state/fields/package-fields.yml" is invalid: field 0.fields.1.fields.4.type: 0.fields.1.fields.4.type must be one of the following: "object"
[2023-07-13T12:42:38.477Z]    4. file "/var/lib/jenkins/workspace/est-manager_integrations_PR-6948/src/github.com/elastic/integrations/packages/azure_application_insights/data_stream/app_state/fields/package-fields.yml" is invalid: field 0.fields.5.type: 0.fields.5.type must be one of the following: "object"
```

- azure_billing
```
[2023-07-13T12:42:37.010Z] Error: checking package failed: linting package failed: found 2 validation errors:
[2023-07-13T12:42:37.010Z]    1. file "/var/lib/jenkins/workspace/est-manager_integrations_PR-6948/src/github.com/elastic/integrations/packages/azure_billing/data_stream/billing/fields/package-fields.yml" is invalid: field 0.fields.1.fields.4.type: 0.fields.1.fields.4.type must be one of the following: "object"
[2023-07-13T12:42:37.010Z]    2. file "/var/lib/jenkins/workspace/est-manager_integrations_PR-6948/src/github.com/elastic/integrations/packages/azure_billing/data_stream/billing/fields/package-fields.yml" is invalid: field 0.fields.5.type: 0.fields.5.type must be one of the following: "object"
```

- hashicorp_vault
```
[2023-07-13T12:40:24.777Z] Error: checking package failed: linting package failed: found 1 validation error:
[2023-07-13T12:40:24.777Z]    1. file "/var/lib/jenkins/workspace/est-manager_integrations_PR-6948/src/github.com/elastic/integrations/packages/hashicorp_vault/data_stream/audit/fields/fields.yml" is invalid: field 0.fields.0.fields.0.fields.10.type: 0.fields.0.fields.0.fields.10.type must be one of the following: "object"
```

**Comment by mrodm** [comment]
Adding the JSON Patches , packages failing running "test integrations" are not due to `elastic-package check -v` command failing. And those 3 packages (azure_application_insights, azure_billing and hashicorp_vault) are run successfully.

https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-6948/3/

**Review by jsoriano — APPROVED** [review]
:+1:

**Comment by tetianakravchenko** [comment]
Hey @mrodm when is it planned to get this changes available in elastic-package?

**Pull request merged**
