### PR TITLE
Add threat_intel package category

### PR DESCRIPTION
**Pull request by jsoriano**
## What does this PR do?

Add threat intel category.

## Why is it important?

Closes https://github.com/elastic/package-spec/issues/222

## Related issues

<!-- Recommended
Link related issues below. Insert the issue link or reference after the word "Closes" if merging this should automatically close it.

- Part of https://github.com/elastic/package-spec/issues/222.

### CODE REVIEW

**Comment by P1llus** [comment]
@jsoriano this one says thread intel instead of threat intel, might be a typo?

**Comment by jsoriano** [comment]
> @jsoriano this one says thread intel instead of threat intel, might be a typo?

Yes :facepalm:

**Comment by jamiehynds** [comment]
@jlind23 if the criteria for additional categories are published, could you please share There are several security categories that I'd really like to include for more granular categorisation and improved discoverability. We currently have 130+ integrations under the 'Security' category.

**Comment by jlind23** [comment]
@jamiehynds nothing was wrote down so far. I'll bring that up again with @mukeshelastic and @akshay-saraswat.

**Comment by jamiehynds** [comment]
Thanks @jlind23 - here's some of the security categories I had in mind but can certainly narrow it down: https://github.com/elastic/integrations/issues/1328

**Comment by akshay-saraswat** [comment]
@jamiehynds let's discuss this. We want to introduce a process so that we don't overdo the categories. I'll reach out with a draft proposal for feedback.

**Pull request merged**
